### ISSUE TITLE
Glfw error

### ISSUE THREAD

**Issue by OlegoroV** [brunoherbelin/vimix#31] opened 2021-04-14 07:33 UTC
After I compiled vimix from source, I have an error when I start program from snap:

Error: Glfw Error 65544: Linux: Failed to watch for joystick connections in /dev/input: No space left on device

I press Close and program starts normally.

**Comment by brunoherbelin** [comment] 2021-05-24 10:13
Hi Oleg
is this still doing it? 
I could not reproduce, so it's hard to detect...

**Comment by linuxnow** [comment] 2021-06-12 16:23
Same error for me in Fedora 34
Error: Glfw Error 65544: Wayland: Failed to connect to display

**Comment by brunoherbelin** [comment] 2022-08-25 13:43
If this error did not occur anymore after a year, I think I can safely close the issue... Let me know otherwise.

**Closed by brunoherbelin** 2022-08-25 13:43 UTC
